---
title: "BIMM 101 Flow Cytometry"
output: html_document
date: "2026-03-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages('tidyverse')
#install.packages('ggplot2')
#install.packages("dplyr")
```


```{r}
library('ggplot2')
library('tidyverse')
library("dplyr")
```

```{r}
setwd("~/Documents/GitHub/KR-BIMM-101")
```


```{r}
TabA0<-read_csv("W26FCBIMM101_2.csv")
QC00<-read_csv("KR Winter 2026 Flow Cytometry - C01_C02 QC.csv")
FC00<-read_csv("KR Winter 2026 Flow Cytometry - C01_C02 Flow.csv")
```

```{r}
###Filter N/A in TabA
TabA1 <- TabA0 %>% filter(!is.na(`Mean FITC (GFP)`))
###Group sections
TabA1$MainSection <- substr(TabA1$Section, 1, 1)

###SectionDf
SecA<-TabA1 %>% 
  filter(MainSection == "A")
SecB<-TabA1 %>% 
  filter(MainSection == "B")
SecC<-TabA1 %>% 
  filter(MainSection == "C")
SecD<-TabA1 %>% 
  filter(MainSection == "D")
SecE<-TabA1 %>% 
  filter(MainSection == "E")
SecF<-TabA1 %>% 
  filter(MainSection == "F")
```

```{r}
###Merge C00 QC Data and Flow Data
merged_C00 <- merge(x = FC00, y = QC00, by = "Sample #", all.x = TRUE)
```

```{r}
###Filter Out FAILED QC
clean_C00<- filter(merged_C00, .by = NULL, .preserve = FALSE)
```


```{r}
###Cleanup Names for PlotA
plotlabs <-c(
  "HDR1: In_ymUkG1"           = "ymUkG1",
  "HDR2: In_yStayGold"        = "yStayGold",
  "HDR3: In_pGK1_mUKG1"       = "pGK1-mUKG1",
  "HDR4: In_pGK1_yUKG1"       = "pGK1-yUKG1",
  "HDR5: In_pGK1_Staygold"    = "pGK1-Staygold",
  "HDR6:In_pGK1_yStaygold"    = "pGK1-yStaygold",
  "HDR7:In_pTDH3_mUKG1"       = "pTDH3-mUKG1",
  "HDR8: In_pTDH3_yUKG1"      = "pTDH3-yUKG1",
  "HDR9: In_pTDH3_Staygold"   = "pTDH3-Staygold",
  "HDR10: In_pTDH3_yStaygold" = "pTDH3-yStaygold",
  "HDR11: In_pTef1_mUKG1"     = "pTef1-mUKG1",
  "HDR12: In_pTef1_yUKG1"     = "pTef1-yUKG1",
  "HDR13: In_pTef1_Staygold"  = "pTef1-Staygold",
  "HDR14: In_pTef1_yStaygold" = "pTef1-yStaygold")

###cleanup names for PlotB
plotlabsB<-c( 
  "HDR1: In_ymUkG1"           = "HDR1",
  "HDR2: In_yStayGold"        = "HDR2",
  "HDR3: In_pGK1_mUKG1"       = "HDR3",
  "HDR4: In_pGK1_yUKG1"       = "HDR4",
  "HDR5: In_pGK1_Staygold"    = "HDR5",
  "HDR6:In_pGK1_yStaygold"    = "HDR6",
  "HDR7:In_pTDH3_mUKG1"       = "HDR7",
  "HDR8: In_pTDH3_yUKG1"      = "HDR8",
  "HDR9: In_pTDH3_Staygold"   = "HDR9",
  "HDR10: In_pTDH3_yStaygold" = "HDR10",
  "HDR11: In_pTef1_mUKG1"     = "HDR11",
  "HDR12: In_pTef1_yUKG1"     = "HDR12",
  "HDR13: In_pTef1_Staygold"  = "HDR13",
  "HDR14: In_pTef1_yStaygold" = "HDR14")
```

```{r}
###Plot 1: Comparing median values and making boxplot for each transformation
Plot1<-ggplot(TabA1,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) across all sections n=262",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))+coord_cartesian(ylim = c(0, 150000))
  
print(Plot1)
#x reorder displays bars from lowest gfp to high, FUN=median decided as best method to approximate center values, jitter shows outlier values a little off center to easily identify
```

```{r}
###Plot A: Comparing median GFP values with boxplot in Section A
PlotA<-ggplot(SecA,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) in Section A n=46",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))
print(PlotA)
```

```{r}
###Plot B: Comparing median GFP values with boxplot in Section B
PlotB<-ggplot(SecB,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) in Section B n=48",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))
print(PlotB)
```

```{r}
###Plot C: Comparing median GFP values with boxplot in Section C
PlotC<-ggplot(SecC,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) in Section C n=45",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))
print(PlotC)  
```
```{r}
###Plot D: Comparing median GFP values with boxplot in Section D
PlotD<-ggplot(SecC,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) in Section D n=40",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))
print(PlotD)  
```


```{r}
###Plot E: Comparing median GFP values with boxplot in Section E
PlotE<-ggplot(SecC,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) in Section E n=35",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))
print(PlotE)  
```


```{r}
###Plot F: Comparing median GFP values with boxplot in Section F
PlotF<-ggplot(SecF,aes(x=reorder(`Transformation type`,`Mean FITC (GFP)`,FUN=median),y=`Mean FITC (GFP)`,fill=`Transformation type`))+
  geom_boxplot(outlier.shape=NA,alpha=0.7)+
  geom_jitter(width = 0.2,alpha = 0.5)+
  labs(title="Mean FITC (GFP) in Section F n=48",x="Transformation Type",y="Mean FITC (GFP)")+
  scale_x_discrete(labels=plotlabs)+theme_minimal()+theme(axis.text.x=element_text(angle=45,hjust = 1))
print(PlotF)  
```

```{r}
###C00 Flow and QC filter for only OK and GOOD quality plot
```



```{r}
###Plot 2:Final comparison using means with SD
summary_df<-TabA1 %>%group_by(`Transformation type`) %>%
  summarize(mean_gfp= mean(`Mean FITC (GFP)`),sd_gfp = sd(`Mean FITC (GFP)`),n = n(),se_gfp = sd_gfp / sqrt(n))

Plot2<-ggplot(summary_df,aes(x = reorder(`Transformation type`,mean_gfp),y=mean_gfp,fill=mean_gfp)) +
  geom_bar(stat = "identity") +scale_fill_gradient(low = "darkgreen", high = "green")+
  geom_errorbar(aes(ymin = mean_gfp - se_gfp, ymax = mean_gfp + se_gfp), width = 0.2) +coord_flip() +
  theme_minimal() +
  labs(title = "Average Mean GFP Expression across sections",subtitle = "Standard Error for error bars",x = "Transformation Type",y = "Average Mean FITC")
print(Plot2)
```

